services:
  - type: web
    name: carpe-diction
    runtime: node
    buildCommand: yarn install && yarn run render-postbuild && cd server && yarn install
    startCommand: cd server && yarn start
    envVars:
      - key: NODE_ENV
        value: production
