services:
  - type: web
    name: carpe-diction
    env: node
    buildCommand: cd client && yarn install && yarn build
    startCommand: cd server && yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: carpe-diction
          property: port
