services:
  - type: web
    name: carpe-diction
    runtime: node
    buildCommand: cd client && yarn install && yarn build && cd ../server && yarn install
    startCommand: cd server && yarn start
    envVars:
      - key: NODE_ENV
        value: production
